#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_webNC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BTLwebNC")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblBaidang(tblBaidang instance);
    partial void UpdatetblBaidang(tblBaidang instance);
    partial void DeletetblBaidang(tblBaidang instance);
    partial void InserttblUser(tblUser instance);
    partial void UpdatetblUser(tblUser instance);
    partial void DeletetblUser(tblUser instance);
    partial void InserttblBinhluan(tblBinhluan instance);
    partial void UpdatetblBinhluan(tblBinhluan instance);
    partial void DeletetblBinhluan(tblBinhluan instance);
    partial void InserttblChude(tblChude instance);
    partial void UpdatetblChude(tblChude instance);
    partial void DeletetblChude(tblChude instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BTLwebNCConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblBaidang> tblBaidangs
		{
			get
			{
				return this.GetTable<tblBaidang>();
			}
		}
		
		public System.Data.Linq.Table<tblUser> tblUsers
		{
			get
			{
				return this.GetTable<tblUser>();
			}
		}
		
		public System.Data.Linq.Table<tblBinhluan> tblBinhluans
		{
			get
			{
				return this.GetTable<tblBinhluan>();
			}
		}
		
		public System.Data.Linq.Table<tblChude> tblChudes
		{
			get
			{
				return this.GetTable<tblChude>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBaidang_delete")]
		public int spBaidang_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PK_iBaidangID", DbType="Int")] System.Nullable<int> pK_iBaidangID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pK_iBaidangID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spLogin_Update")]
		public int spLogin_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sAnh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bQuyen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sTen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sName, sPassword, sAnh, bQuyen, sTen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBaidang_getbyID")]
		public ISingleResult<spBaidang_getbyIDResult> spBaidang_getbyID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PK_iBaidangID", DbType="Int")] System.Nullable<int> pK_iBaidangID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pK_iBaidangID);
			return ((ISingleResult<spBaidang_getbyIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBaidang_Hienluotxem")]
		public int spBaidang_Hienluotxem([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PK_iBaidangID", DbType="Int")] System.Nullable<int> pK_iBaidangID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> iLuotxem)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pK_iBaidangID, iLuotxem);
			iLuotxem = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBaidang_Insert")]
		public int spBaidang_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string sTieude, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string sNoidung, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> iLuotxem, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dNgaydang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_iChudeID", DbType="Int")] System.Nullable<int> fK_iChudeID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sAnh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTieude, sNoidung, iLuotxem, dNgaydang, fK_iChudeID, sAnh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBaidang_Luotxem")]
		public int spBaidang_Luotxem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> iLuotxem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PK_iBaidangID", DbType="Int")] System.Nullable<int> pK_iBaidangID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iLuotxem, pK_iBaidangID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBaidang_new")]
		public ISingleResult<spBaidang_newResult> spBaidang_new()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spBaidang_newResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBaidang_Update")]
		public int spBaidang_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PK_iBaidangID", DbType="Int")] System.Nullable<int> pK_iBaidangID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string sTieude, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string sNoidung, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> iLuotxem, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dNgaydang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_iChudeID", DbType="Int")] System.Nullable<int> fK_iChudeID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sAnh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pK_iBaidangID, sTieude, sNoidung, iLuotxem, dNgaydang, fK_iChudeID, sAnh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBinhluan_getbyBaidangID")]
		public ISingleResult<spBinhluan_getbyBaidangIDResult> spBinhluan_getbyBaidangID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_iBaidangID", DbType="Int")] System.Nullable<int> fK_iBaidangID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fK_iBaidangID);
			return ((ISingleResult<spBinhluan_getbyBaidangIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBinhluan_Insert")]
		public int spBinhluan_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string sNoidung, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_iBaidangID", DbType="Int")] System.Nullable<int> fK_iBaidangID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_sName", DbType="NVarChar(50)")] string fK_sName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sNoidung, fK_iBaidangID, fK_sName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spChude_get")]
		public ISingleResult<spChude_getResult> spChude_get()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spChude_getResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spChude_getbyID")]
		public ISingleResult<spChude_getbyIDResult> spChude_getbyID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PK_iChudeID", DbType="Int")] System.Nullable<int> pK_iChudeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pK_iChudeID);
			return ((ISingleResult<spChude_getbyIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spLogin_delete")]
		public int spLogin_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spLogin_get")]
		public ISingleResult<spLogin_getResult> spLogin_get([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sPassword)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sName, sPassword);
			return ((ISingleResult<spLogin_getResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spLogin_getName")]
		public ISingleResult<spLogin_getNameResult> spLogin_getName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sName);
			return ((ISingleResult<spLogin_getNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spLogin_insert")]
		public int spLogin_insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sAnh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bQuyen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sTen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sName, sPassword, sAnh, bQuyen, sTen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBinhluan_getbyBaidang")]
		public ISingleResult<spBinhluan_getbyBaidangResult> spBinhluan_getbyBaidang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_iBaidangID", DbType="Int")] System.Nullable<int> fK_iBaidangID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fK_iBaidangID);
			return ((ISingleResult<spBinhluan_getbyBaidangResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBaidang_getbyChude")]
		public ISingleResult<spBaidang_getbyChudeResult> spBaidang_getbyChude([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_iChudeID", DbType="Int")] System.Nullable<int> fK_iChudeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fK_iChudeID);
			return ((ISingleResult<spBaidang_getbyChudeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBaidang_random")]
		public ISingleResult<spBaidang_randomResult> spBaidang_random()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spBaidang_randomResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBaidang_find")]
		public ISingleResult<spBaidang_findResult> spBaidang_find([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string sTieude, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string dNgaydang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTieude, dNgaydang);
			return ((ISingleResult<spBaidang_findResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spBinhluan_delete")]
		public int spBinhluan_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PK_iBinhluanID", DbType="Int")] System.Nullable<int> pK_iBinhluanID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pK_iBinhluanID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spLogin_Update1")]
		public int spLogin_Update1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sTen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sName, sPassword, sTen);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBaidang")]
	public partial class tblBaidang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_iBaidangID;
		
		private string _sTieude;
		
		private string _sNoidung;
		
		private int _iLuotxem;
		
		private System.Nullable<System.DateTime> _dNgaydang;
		
		private System.Nullable<int> _FK_iChudeID;
		
		private EntitySet<tblBinhluan> _tblBinhluans;
		
		private EntityRef<tblChude> _tblChude;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_iBaidangIDChanging(int value);
    partial void OnPK_iBaidangIDChanged();
    partial void OnsTieudeChanging(string value);
    partial void OnsTieudeChanged();
    partial void OnsNoidungChanging(string value);
    partial void OnsNoidungChanged();
    partial void OniLuotxemChanging(int value);
    partial void OniLuotxemChanged();
    partial void OndNgaydangChanging(System.Nullable<System.DateTime> value);
    partial void OndNgaydangChanged();
    partial void OnFK_iChudeIDChanging(System.Nullable<int> value);
    partial void OnFK_iChudeIDChanged();
    #endregion
		
		public tblBaidang()
		{
			this._tblBinhluans = new EntitySet<tblBinhluan>(new Action<tblBinhluan>(this.attach_tblBinhluans), new Action<tblBinhluan>(this.detach_tblBinhluans));
			this._tblChude = default(EntityRef<tblChude>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_iBaidangID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PK_iBaidangID
		{
			get
			{
				return this._PK_iBaidangID;
			}
			set
			{
				if ((this._PK_iBaidangID != value))
				{
					this.OnPK_iBaidangIDChanging(value);
					this.SendPropertyChanging();
					this._PK_iBaidangID = value;
					this.SendPropertyChanged("PK_iBaidangID");
					this.OnPK_iBaidangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTieude", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string sTieude
		{
			get
			{
				return this._sTieude;
			}
			set
			{
				if ((this._sTieude != value))
				{
					this.OnsTieudeChanging(value);
					this.SendPropertyChanging();
					this._sTieude = value;
					this.SendPropertyChanged("sTieude");
					this.OnsTieudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sNoidung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sNoidung
		{
			get
			{
				return this._sNoidung;
			}
			set
			{
				if ((this._sNoidung != value))
				{
					this.OnsNoidungChanging(value);
					this.SendPropertyChanging();
					this._sNoidung = value;
					this.SendPropertyChanged("sNoidung");
					this.OnsNoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iLuotxem", DbType="Int NOT NULL")]
		public int iLuotxem
		{
			get
			{
				return this._iLuotxem;
			}
			set
			{
				if ((this._iLuotxem != value))
				{
					this.OniLuotxemChanging(value);
					this.SendPropertyChanging();
					this._iLuotxem = value;
					this.SendPropertyChanged("iLuotxem");
					this.OniLuotxemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dNgaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> dNgaydang
		{
			get
			{
				return this._dNgaydang;
			}
			set
			{
				if ((this._dNgaydang != value))
				{
					this.OndNgaydangChanging(value);
					this.SendPropertyChanging();
					this._dNgaydang = value;
					this.SendPropertyChanged("dNgaydang");
					this.OndNgaydangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_iChudeID", DbType="Int")]
		public System.Nullable<int> FK_iChudeID
		{
			get
			{
				return this._FK_iChudeID;
			}
			set
			{
				if ((this._FK_iChudeID != value))
				{
					if (this._tblChude.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_iChudeIDChanging(value);
					this.SendPropertyChanging();
					this._FK_iChudeID = value;
					this.SendPropertyChanged("FK_iChudeID");
					this.OnFK_iChudeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBaidang_tblBinhluan", Storage="_tblBinhluans", ThisKey="PK_iBaidangID", OtherKey="FK_iBaidangID")]
		public EntitySet<tblBinhluan> tblBinhluans
		{
			get
			{
				return this._tblBinhluans;
			}
			set
			{
				this._tblBinhluans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChude_tblBaidang", Storage="_tblChude", ThisKey="FK_iChudeID", OtherKey="PK_iChudeID", IsForeignKey=true)]
		public tblChude tblChude
		{
			get
			{
				return this._tblChude.Entity;
			}
			set
			{
				tblChude previousValue = this._tblChude.Entity;
				if (((previousValue != value) 
							|| (this._tblChude.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblChude.Entity = null;
						previousValue.tblBaidangs.Remove(this);
					}
					this._tblChude.Entity = value;
					if ((value != null))
					{
						value.tblBaidangs.Add(this);
						this._FK_iChudeID = value.PK_iChudeID;
					}
					else
					{
						this._FK_iChudeID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblChude");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblBinhluans(tblBinhluan entity)
		{
			this.SendPropertyChanging();
			entity.tblBaidang = this;
		}
		
		private void detach_tblBinhluans(tblBinhluan entity)
		{
			this.SendPropertyChanging();
			entity.tblBaidang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUser")]
	public partial class tblUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_iUserID;
		
		private string _sName;
		
		private string _sPassword;
		
		private EntitySet<tblBinhluan> _tblBinhluans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_iUserIDChanging(int value);
    partial void OnPK_iUserIDChanged();
    partial void OnsNameChanging(string value);
    partial void OnsNameChanged();
    partial void OnsPasswordChanging(string value);
    partial void OnsPasswordChanged();
    #endregion
		
		public tblUser()
		{
			this._tblBinhluans = new EntitySet<tblBinhluan>(new Action<tblBinhluan>(this.attach_tblBinhluans), new Action<tblBinhluan>(this.detach_tblBinhluans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_iUserID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PK_iUserID
		{
			get
			{
				return this._PK_iUserID;
			}
			set
			{
				if ((this._PK_iUserID != value))
				{
					this.OnPK_iUserIDChanging(value);
					this.SendPropertyChanging();
					this._PK_iUserID = value;
					this.SendPropertyChanged("PK_iUserID");
					this.OnPK_iUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sName", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string sName
		{
			get
			{
				return this._sName;
			}
			set
			{
				if ((this._sName != value))
				{
					this.OnsNameChanging(value);
					this.SendPropertyChanging();
					this._sName = value;
					this.SendPropertyChanged("sName");
					this.OnsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPassword", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string sPassword
		{
			get
			{
				return this._sPassword;
			}
			set
			{
				if ((this._sPassword != value))
				{
					this.OnsPasswordChanging(value);
					this.SendPropertyChanging();
					this._sPassword = value;
					this.SendPropertyChanged("sPassword");
					this.OnsPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUser_tblBinhluan", Storage="_tblBinhluans", ThisKey="PK_iUserID", OtherKey="FK_iUserID")]
		public EntitySet<tblBinhluan> tblBinhluans
		{
			get
			{
				return this._tblBinhluans;
			}
			set
			{
				this._tblBinhluans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblBinhluans(tblBinhluan entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = this;
		}
		
		private void detach_tblBinhluans(tblBinhluan entity)
		{
			this.SendPropertyChanging();
			entity.tblUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBinhluan")]
	public partial class tblBinhluan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_iBinhluanID;
		
		private string _sNoidung;
		
		private int _FK_iBaidangID;
		
		private int _FK_iUserID;
		
		private EntityRef<tblBaidang> _tblBaidang;
		
		private EntityRef<tblUser> _tblUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_iBinhluanIDChanging(int value);
    partial void OnPK_iBinhluanIDChanged();
    partial void OnsNoidungChanging(string value);
    partial void OnsNoidungChanged();
    partial void OnFK_iBaidangIDChanging(int value);
    partial void OnFK_iBaidangIDChanged();
    partial void OnFK_iUserIDChanging(int value);
    partial void OnFK_iUserIDChanged();
    #endregion
		
		public tblBinhluan()
		{
			this._tblBaidang = default(EntityRef<tblBaidang>);
			this._tblUser = default(EntityRef<tblUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_iBinhluanID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PK_iBinhluanID
		{
			get
			{
				return this._PK_iBinhluanID;
			}
			set
			{
				if ((this._PK_iBinhluanID != value))
				{
					this.OnPK_iBinhluanIDChanging(value);
					this.SendPropertyChanging();
					this._PK_iBinhluanID = value;
					this.SendPropertyChanged("PK_iBinhluanID");
					this.OnPK_iBinhluanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sNoidung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sNoidung
		{
			get
			{
				return this._sNoidung;
			}
			set
			{
				if ((this._sNoidung != value))
				{
					this.OnsNoidungChanging(value);
					this.SendPropertyChanging();
					this._sNoidung = value;
					this.SendPropertyChanged("sNoidung");
					this.OnsNoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_iBaidangID", DbType="Int NOT NULL")]
		public int FK_iBaidangID
		{
			get
			{
				return this._FK_iBaidangID;
			}
			set
			{
				if ((this._FK_iBaidangID != value))
				{
					if (this._tblBaidang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_iBaidangIDChanging(value);
					this.SendPropertyChanging();
					this._FK_iBaidangID = value;
					this.SendPropertyChanged("FK_iBaidangID");
					this.OnFK_iBaidangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_iUserID", DbType="Int NOT NULL")]
		public int FK_iUserID
		{
			get
			{
				return this._FK_iUserID;
			}
			set
			{
				if ((this._FK_iUserID != value))
				{
					if (this._tblUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_iUserIDChanging(value);
					this.SendPropertyChanging();
					this._FK_iUserID = value;
					this.SendPropertyChanged("FK_iUserID");
					this.OnFK_iUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBaidang_tblBinhluan", Storage="_tblBaidang", ThisKey="FK_iBaidangID", OtherKey="PK_iBaidangID", IsForeignKey=true)]
		public tblBaidang tblBaidang
		{
			get
			{
				return this._tblBaidang.Entity;
			}
			set
			{
				tblBaidang previousValue = this._tblBaidang.Entity;
				if (((previousValue != value) 
							|| (this._tblBaidang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblBaidang.Entity = null;
						previousValue.tblBinhluans.Remove(this);
					}
					this._tblBaidang.Entity = value;
					if ((value != null))
					{
						value.tblBinhluans.Add(this);
						this._FK_iBaidangID = value.PK_iBaidangID;
					}
					else
					{
						this._FK_iBaidangID = default(int);
					}
					this.SendPropertyChanged("tblBaidang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUser_tblBinhluan", Storage="_tblUser", ThisKey="FK_iUserID", OtherKey="PK_iUserID", IsForeignKey=true)]
		public tblUser tblUser
		{
			get
			{
				return this._tblUser.Entity;
			}
			set
			{
				tblUser previousValue = this._tblUser.Entity;
				if (((previousValue != value) 
							|| (this._tblUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUser.Entity = null;
						previousValue.tblBinhluans.Remove(this);
					}
					this._tblUser.Entity = value;
					if ((value != null))
					{
						value.tblBinhluans.Add(this);
						this._FK_iUserID = value.PK_iUserID;
					}
					else
					{
						this._FK_iUserID = default(int);
					}
					this.SendPropertyChanged("tblUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChude")]
	public partial class tblChude : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_iChudeID;
		
		private string _sTenchude;
		
		private EntitySet<tblBaidang> _tblBaidangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_iChudeIDChanging(int value);
    partial void OnPK_iChudeIDChanged();
    partial void OnsTenchudeChanging(string value);
    partial void OnsTenchudeChanged();
    #endregion
		
		public tblChude()
		{
			this._tblBaidangs = new EntitySet<tblBaidang>(new Action<tblBaidang>(this.attach_tblBaidangs), new Action<tblBaidang>(this.detach_tblBaidangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_iChudeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PK_iChudeID
		{
			get
			{
				return this._PK_iChudeID;
			}
			set
			{
				if ((this._PK_iChudeID != value))
				{
					this.OnPK_iChudeIDChanging(value);
					this.SendPropertyChanging();
					this._PK_iChudeID = value;
					this.SendPropertyChanged("PK_iChudeID");
					this.OnPK_iChudeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTenchude", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sTenchude
		{
			get
			{
				return this._sTenchude;
			}
			set
			{
				if ((this._sTenchude != value))
				{
					this.OnsTenchudeChanging(value);
					this.SendPropertyChanging();
					this._sTenchude = value;
					this.SendPropertyChanged("sTenchude");
					this.OnsTenchudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChude_tblBaidang", Storage="_tblBaidangs", ThisKey="PK_iChudeID", OtherKey="FK_iChudeID")]
		public EntitySet<tblBaidang> tblBaidangs
		{
			get
			{
				return this._tblBaidangs;
			}
			set
			{
				this._tblBaidangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblBaidangs(tblBaidang entity)
		{
			this.SendPropertyChanging();
			entity.tblChude = this;
		}
		
		private void detach_tblBaidangs(tblBaidang entity)
		{
			this.SendPropertyChanging();
			entity.tblChude = null;
		}
	}
	
	public partial class spBaidang_getbyIDResult
	{
		
		private int _PK_iBaidangID;
		
		private string _sTieude;
		
		private string _sNoidung;
		
		private System.Nullable<int> _iLuotxem;
		
		private System.Nullable<System.DateTime> _dNgaydang;
		
		private System.Nullable<int> _FK_iChudeID;
		
		private string _sAnh;
		
		public spBaidang_getbyIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_iBaidangID", DbType="Int NOT NULL")]
		public int PK_iBaidangID
		{
			get
			{
				return this._PK_iBaidangID;
			}
			set
			{
				if ((this._PK_iBaidangID != value))
				{
					this._PK_iBaidangID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTieude", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string sTieude
		{
			get
			{
				return this._sTieude;
			}
			set
			{
				if ((this._sTieude != value))
				{
					this._sTieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sNoidung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sNoidung
		{
			get
			{
				return this._sNoidung;
			}
			set
			{
				if ((this._sNoidung != value))
				{
					this._sNoidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iLuotxem", DbType="Int")]
		public System.Nullable<int> iLuotxem
		{
			get
			{
				return this._iLuotxem;
			}
			set
			{
				if ((this._iLuotxem != value))
				{
					this._iLuotxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dNgaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> dNgaydang
		{
			get
			{
				return this._dNgaydang;
			}
			set
			{
				if ((this._dNgaydang != value))
				{
					this._dNgaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_iChudeID", DbType="Int")]
		public System.Nullable<int> FK_iChudeID
		{
			get
			{
				return this._FK_iChudeID;
			}
			set
			{
				if ((this._FK_iChudeID != value))
				{
					this._FK_iChudeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sAnh", DbType="NVarChar(50)")]
		public string sAnh
		{
			get
			{
				return this._sAnh;
			}
			set
			{
				if ((this._sAnh != value))
				{
					this._sAnh = value;
				}
			}
		}
	}
	
	public partial class spBaidang_newResult
	{
		
		private int _PK_iBaidangID;
		
		private string _sTieude;
		
		private string _sNoidung;
		
		private System.Nullable<int> _iLuotxem;
		
		private System.Nullable<System.DateTime> _dNgaydang;
		
		private System.Nullable<int> _FK_iChudeID;
		
		private string _sAnh;
		
		public spBaidang_newResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_iBaidangID", DbType="Int NOT NULL")]
		public int PK_iBaidangID
		{
			get
			{
				return this._PK_iBaidangID;
			}
			set
			{
				if ((this._PK_iBaidangID != value))
				{
					this._PK_iBaidangID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTieude", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string sTieude
		{
			get
			{
				return this._sTieude;
			}
			set
			{
				if ((this._sTieude != value))
				{
					this._sTieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sNoidung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sNoidung
		{
			get
			{
				return this._sNoidung;
			}
			set
			{
				if ((this._sNoidung != value))
				{
					this._sNoidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iLuotxem", DbType="Int")]
		public System.Nullable<int> iLuotxem
		{
			get
			{
				return this._iLuotxem;
			}
			set
			{
				if ((this._iLuotxem != value))
				{
					this._iLuotxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dNgaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> dNgaydang
		{
			get
			{
				return this._dNgaydang;
			}
			set
			{
				if ((this._dNgaydang != value))
				{
					this._dNgaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_iChudeID", DbType="Int")]
		public System.Nullable<int> FK_iChudeID
		{
			get
			{
				return this._FK_iChudeID;
			}
			set
			{
				if ((this._FK_iChudeID != value))
				{
					this._FK_iChudeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sAnh", DbType="NVarChar(50)")]
		public string sAnh
		{
			get
			{
				return this._sAnh;
			}
			set
			{
				if ((this._sAnh != value))
				{
					this._sAnh = value;
				}
			}
		}
	}
	
	public partial class spBinhluan_getbyBaidangIDResult
	{
		
		private int _PK_iBinhluanID;
		
		private string _sNoidung;
		
		private int _FK_iBaidangID;
		
		private string _FK_sName;
		
		public spBinhluan_getbyBaidangIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_iBinhluanID", DbType="Int NOT NULL")]
		public int PK_iBinhluanID
		{
			get
			{
				return this._PK_iBinhluanID;
			}
			set
			{
				if ((this._PK_iBinhluanID != value))
				{
					this._PK_iBinhluanID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sNoidung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sNoidung
		{
			get
			{
				return this._sNoidung;
			}
			set
			{
				if ((this._sNoidung != value))
				{
					this._sNoidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_iBaidangID", DbType="Int NOT NULL")]
		public int FK_iBaidangID
		{
			get
			{
				return this._FK_iBaidangID;
			}
			set
			{
				if ((this._FK_iBaidangID != value))
				{
					this._FK_iBaidangID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_sName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FK_sName
		{
			get
			{
				return this._FK_sName;
			}
			set
			{
				if ((this._FK_sName != value))
				{
					this._FK_sName = value;
				}
			}
		}
	}
	
	public partial class spChude_getResult
	{
		
		private int _PK_iChudeID;
		
		private string _sTenchude;
		
		public spChude_getResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_iChudeID", DbType="Int NOT NULL")]
		public int PK_iChudeID
		{
			get
			{
				return this._PK_iChudeID;
			}
			set
			{
				if ((this._PK_iChudeID != value))
				{
					this._PK_iChudeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTenchude", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sTenchude
		{
			get
			{
				return this._sTenchude;
			}
			set
			{
				if ((this._sTenchude != value))
				{
					this._sTenchude = value;
				}
			}
		}
	}
	
	public partial class spChude_getbyIDResult
	{
		
		private int _PK_iChudeID;
		
		private string _sTenchude;
		
		public spChude_getbyIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_iChudeID", DbType="Int NOT NULL")]
		public int PK_iChudeID
		{
			get
			{
				return this._PK_iChudeID;
			}
			set
			{
				if ((this._PK_iChudeID != value))
				{
					this._PK_iChudeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTenchude", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sTenchude
		{
			get
			{
				return this._sTenchude;
			}
			set
			{
				if ((this._sTenchude != value))
				{
					this._sTenchude = value;
				}
			}
		}
	}
	
	public partial class spLogin_getResult
	{
		
		private int _iUserID;
		
		private string _sName;
		
		private string _sPassword;
		
		private string _sAnh;
		
		private bool _bQuyen;
		
		private string _sTen;
		
		public spLogin_getResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iUserID", DbType="Int NOT NULL")]
		public int iUserID
		{
			get
			{
				return this._iUserID;
			}
			set
			{
				if ((this._iUserID != value))
				{
					this._iUserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sName
		{
			get
			{
				return this._sName;
			}
			set
			{
				if ((this._sName != value))
				{
					this._sName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPassword", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sPassword
		{
			get
			{
				return this._sPassword;
			}
			set
			{
				if ((this._sPassword != value))
				{
					this._sPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sAnh", DbType="NVarChar(50)")]
		public string sAnh
		{
			get
			{
				return this._sAnh;
			}
			set
			{
				if ((this._sAnh != value))
				{
					this._sAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bQuyen", DbType="Bit NOT NULL")]
		public bool bQuyen
		{
			get
			{
				return this._bQuyen;
			}
			set
			{
				if ((this._bQuyen != value))
				{
					this._bQuyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTen", DbType="NVarChar(50)")]
		public string sTen
		{
			get
			{
				return this._sTen;
			}
			set
			{
				if ((this._sTen != value))
				{
					this._sTen = value;
				}
			}
		}
	}
	
	public partial class spLogin_getNameResult
	{
		
		private int _iUserID;
		
		private string _sName;
		
		private string _sPassword;
		
		private string _sAnh;
		
		private bool _bQuyen;
		
		private string _sTen;
		
		public spLogin_getNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iUserID", DbType="Int NOT NULL")]
		public int iUserID
		{
			get
			{
				return this._iUserID;
			}
			set
			{
				if ((this._iUserID != value))
				{
					this._iUserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sName
		{
			get
			{
				return this._sName;
			}
			set
			{
				if ((this._sName != value))
				{
					this._sName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPassword", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sPassword
		{
			get
			{
				return this._sPassword;
			}
			set
			{
				if ((this._sPassword != value))
				{
					this._sPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sAnh", DbType="NVarChar(50)")]
		public string sAnh
		{
			get
			{
				return this._sAnh;
			}
			set
			{
				if ((this._sAnh != value))
				{
					this._sAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bQuyen", DbType="Bit NOT NULL")]
		public bool bQuyen
		{
			get
			{
				return this._bQuyen;
			}
			set
			{
				if ((this._bQuyen != value))
				{
					this._bQuyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTen", DbType="NVarChar(50)")]
		public string sTen
		{
			get
			{
				return this._sTen;
			}
			set
			{
				if ((this._sTen != value))
				{
					this._sTen = value;
				}
			}
		}
	}
	
	public partial class spBinhluan_getbyBaidangResult
	{
		
		private string _sTen;
		
		private string _sNoidung;
		
		private int _FK_iBaidangID;
		
		private string _sAnh;
		
		private int _iUserID;
		
		private string _sName;
		
		private int _PK_iBinhluanID;
		
		public spBinhluan_getbyBaidangResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTen", DbType="NVarChar(50)")]
		public string sTen
		{
			get
			{
				return this._sTen;
			}
			set
			{
				if ((this._sTen != value))
				{
					this._sTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sNoidung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sNoidung
		{
			get
			{
				return this._sNoidung;
			}
			set
			{
				if ((this._sNoidung != value))
				{
					this._sNoidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_iBaidangID", DbType="Int NOT NULL")]
		public int FK_iBaidangID
		{
			get
			{
				return this._FK_iBaidangID;
			}
			set
			{
				if ((this._FK_iBaidangID != value))
				{
					this._FK_iBaidangID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sAnh", DbType="NVarChar(50)")]
		public string sAnh
		{
			get
			{
				return this._sAnh;
			}
			set
			{
				if ((this._sAnh != value))
				{
					this._sAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iUserID", DbType="Int NOT NULL")]
		public int iUserID
		{
			get
			{
				return this._iUserID;
			}
			set
			{
				if ((this._iUserID != value))
				{
					this._iUserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sName
		{
			get
			{
				return this._sName;
			}
			set
			{
				if ((this._sName != value))
				{
					this._sName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_iBinhluanID", DbType="Int NOT NULL")]
		public int PK_iBinhluanID
		{
			get
			{
				return this._PK_iBinhluanID;
			}
			set
			{
				if ((this._PK_iBinhluanID != value))
				{
					this._PK_iBinhluanID = value;
				}
			}
		}
	}
	
	public partial class spBaidang_getbyChudeResult
	{
		
		private int _PK_iBaidangID;
		
		private string _sTieude;
		
		private string _sNoidung;
		
		private System.Nullable<int> _iLuotxem;
		
		private System.Nullable<System.DateTime> _dNgaydang;
		
		private System.Nullable<int> _FK_iChudeID;
		
		private string _sAnh;
		
		public spBaidang_getbyChudeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_iBaidangID", DbType="Int NOT NULL")]
		public int PK_iBaidangID
		{
			get
			{
				return this._PK_iBaidangID;
			}
			set
			{
				if ((this._PK_iBaidangID != value))
				{
					this._PK_iBaidangID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTieude", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string sTieude
		{
			get
			{
				return this._sTieude;
			}
			set
			{
				if ((this._sTieude != value))
				{
					this._sTieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sNoidung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sNoidung
		{
			get
			{
				return this._sNoidung;
			}
			set
			{
				if ((this._sNoidung != value))
				{
					this._sNoidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iLuotxem", DbType="Int")]
		public System.Nullable<int> iLuotxem
		{
			get
			{
				return this._iLuotxem;
			}
			set
			{
				if ((this._iLuotxem != value))
				{
					this._iLuotxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dNgaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> dNgaydang
		{
			get
			{
				return this._dNgaydang;
			}
			set
			{
				if ((this._dNgaydang != value))
				{
					this._dNgaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_iChudeID", DbType="Int")]
		public System.Nullable<int> FK_iChudeID
		{
			get
			{
				return this._FK_iChudeID;
			}
			set
			{
				if ((this._FK_iChudeID != value))
				{
					this._FK_iChudeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sAnh", DbType="NVarChar(50)")]
		public string sAnh
		{
			get
			{
				return this._sAnh;
			}
			set
			{
				if ((this._sAnh != value))
				{
					this._sAnh = value;
				}
			}
		}
	}
	
	public partial class spBaidang_randomResult
	{
		
		private int _PK_iBaidangID;
		
		private string _sTieude;
		
		private string _sNoidung;
		
		private System.Nullable<int> _iLuotxem;
		
		private System.Nullable<System.DateTime> _dNgaydang;
		
		private System.Nullable<int> _FK_iChudeID;
		
		private string _sAnh;
		
		public spBaidang_randomResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_iBaidangID", DbType="Int NOT NULL")]
		public int PK_iBaidangID
		{
			get
			{
				return this._PK_iBaidangID;
			}
			set
			{
				if ((this._PK_iBaidangID != value))
				{
					this._PK_iBaidangID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTieude", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string sTieude
		{
			get
			{
				return this._sTieude;
			}
			set
			{
				if ((this._sTieude != value))
				{
					this._sTieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sNoidung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sNoidung
		{
			get
			{
				return this._sNoidung;
			}
			set
			{
				if ((this._sNoidung != value))
				{
					this._sNoidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iLuotxem", DbType="Int")]
		public System.Nullable<int> iLuotxem
		{
			get
			{
				return this._iLuotxem;
			}
			set
			{
				if ((this._iLuotxem != value))
				{
					this._iLuotxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dNgaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> dNgaydang
		{
			get
			{
				return this._dNgaydang;
			}
			set
			{
				if ((this._dNgaydang != value))
				{
					this._dNgaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_iChudeID", DbType="Int")]
		public System.Nullable<int> FK_iChudeID
		{
			get
			{
				return this._FK_iChudeID;
			}
			set
			{
				if ((this._FK_iChudeID != value))
				{
					this._FK_iChudeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sAnh", DbType="NVarChar(50)")]
		public string sAnh
		{
			get
			{
				return this._sAnh;
			}
			set
			{
				if ((this._sAnh != value))
				{
					this._sAnh = value;
				}
			}
		}
	}
	
	public partial class spBaidang_findResult
	{
		
		private int _PK_iBaidangID;
		
		private string _sTieude;
		
		private string _sNoidung;
		
		private System.Nullable<int> _iLuotxem;
		
		private System.Nullable<System.DateTime> _dNgaydang;
		
		private System.Nullable<int> _FK_iChudeID;
		
		private string _sAnh;
		
		public spBaidang_findResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_iBaidangID", DbType="Int NOT NULL")]
		public int PK_iBaidangID
		{
			get
			{
				return this._PK_iBaidangID;
			}
			set
			{
				if ((this._PK_iBaidangID != value))
				{
					this._PK_iBaidangID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTieude", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string sTieude
		{
			get
			{
				return this._sTieude;
			}
			set
			{
				if ((this._sTieude != value))
				{
					this._sTieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sNoidung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sNoidung
		{
			get
			{
				return this._sNoidung;
			}
			set
			{
				if ((this._sNoidung != value))
				{
					this._sNoidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iLuotxem", DbType="Int")]
		public System.Nullable<int> iLuotxem
		{
			get
			{
				return this._iLuotxem;
			}
			set
			{
				if ((this._iLuotxem != value))
				{
					this._iLuotxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dNgaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> dNgaydang
		{
			get
			{
				return this._dNgaydang;
			}
			set
			{
				if ((this._dNgaydang != value))
				{
					this._dNgaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_iChudeID", DbType="Int")]
		public System.Nullable<int> FK_iChudeID
		{
			get
			{
				return this._FK_iChudeID;
			}
			set
			{
				if ((this._FK_iChudeID != value))
				{
					this._FK_iChudeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sAnh", DbType="NVarChar(50)")]
		public string sAnh
		{
			get
			{
				return this._sAnh;
			}
			set
			{
				if ((this._sAnh != value))
				{
					this._sAnh = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
